# -*- coding: utf-8 -*-
"""TSNE

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d5c3n2jEtkQw8QGY2Dc9yUjEdNVc6HBR
"""

from mpl_toolkits.mplot3d import Axes3D
from matplotlib import pyplot as plt
from MulticoreTSNE import MulticoreTSNE as TSNE
import pickle
import numpy as np


def get_similarity(a, b):
    dist = np.linalg.norm(a-b)
    return dist


f = open("embeddings_v5.obj", 'rb')
embeddingList = pickle.load(f)

key, attribute = zip(*[(line[0], line[1]) for line in embeddingList])
attribute = np.array([l[0] for l in attribute])

with open('labels.tsv', 'w') as f:
    f.write('\n'.join(key))

with open('embeddings.tsv', 'w') as f:
    f.write("\n".join(["\t".join([str(i) for i in l]) for l in attribute]))
# embeddings = TSNE(n_jobs=4, n_components=3,
#                   perplexity=30, learning_rate=50).fit_transform(attribute)

# vis_x = embeddings[:, 0]
# vis_y = embeddings[:, 1]
# vis_z = embeddings[:, 2]
# fig = plt.figure()
# ax = Axes3D(fig)
# ax.scatter(vis_x, vis_y, vis_z, cmap=plt.cm.get_cmap("jet", 10), marker='.')
# for i, (x, y, z, zdir, key) in enumerate(zip(vis_x, vis_y, vis_z, [None]*len(embeddings), key)):
#     if i % 10 == 0:
#         ax.text(x, y, z, s=key, zdir=zdir)
# plt.show()
